#!/bin/bash
# The interpreter used to execute the script

#“#SBATCH” directives that convey submission options:

#SBATCH --job-name=multiQC_ECCPaper1
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=4g
#SBATCH --time=8:00:00
#SBATCH --account=bfoxman0
#SBATCH --partition=standard
#SBATCH --output=/nfs/turbo/sph-bfoxman/People/wangmk/ECCPaper1/WGS/multiQCresults/%x-%j.log
#SBATCH --error=/nfs/turbo/sph-bfoxman/People/wangmk/ECCPaper1/WGS/multiQCresults/%x-%j-error.log

trim_dir=/nfs/turbo/sph-bfoxman/People/wangmk/ECCPaper1/WGS/post_trim/FASTQC/
decontam_dir=/nfs/turbo/sph-bfoxman/People/wangmk/ECCPaper1/WGS/post_HR/FASTQC/
out_dir=/nfs/turbo/sph-bfoxman/People/wangmk/ECCPaper1/WGS/multiQCresults/

module load Bioinformatics
source /home/wangmk/.bashrc
micromamba activate multiqc

multiqc -f ${trim_dir}*_paired_fastqc* -n pairedPosttrim -o ${out_dir}
multiqc -f ${trim_dir}*unpaired_fastqc* -n unpairedPosttrim -o ${out_dir}

multiqc -f ${decontam_dir}*_paired_decon_fastqc* -n pairedPostHR -o ${out_dir}
multiqc -f ${decontam_dir}*unpaired_decon_fastqc* -n unpairedPostHR -o ${out_dir}
